[tool.ruff]
line-length = 100
target-version = "py311"
exclude = ["venv", ".venv", "build", "dist"]

[tool.ruff.lint]
# 기존 select/ignore를 이 섹션으로 이동
select = ["E", "F", "W", "I", "UP", "B"]
ignore = ["E203"]

[tool.ruff.format]
quote-style = "preserve"
indent-style = "space"
skip-magic-trailing-comma = false
